#!/usr/bin/env php
<?php

declare(strict_types=1);

const CONVERSION_MARKER = '.bootstrapmade-php-conversion';

function fail(string $message, int $code = 1): never
{
    fwrite(STDERR, "Error: {$message}\n");
    exit($code);
}

function usage(): never
{
    $script = basename(__FILE__);
    fwrite(STDERR, <<<TEXT
Usage:
  php scripts/{$script} --source=/path/to/export --output=/path/to/php-site [--layout=index.html] [--force]

Options:
  --source   BootstrapMade export directory containing HTML pages.
  --output   New directory for the converted PHP site. It must differ from source.
  --layout   Page used as the shared header/nav/footer template (default: index.html).
  --force    Replace a prior output created by this converter.

TEXT);
    exit(2);
}

function canonicalPath(string $path): string
{
    $resolved = realpath($path);
    return $resolved !== false ? rtrim($resolved, DIRECTORY_SEPARATOR) : rtrim($path, DIRECTORY_SEPARATOR);
}

function removeDirectory(string $directory): void
{
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );

    foreach ($iterator as $item) {
        $path = $item->getPathname();
        $item->isDir() ? rmdir($path) : unlink($path);
    }

    rmdir($directory);
}

function prepareOutput(string $source, string $output, bool $force): void
{
    if (canonicalPath($source) === canonicalPath($output)) {
        fail('Source and output must be different directories. In-place conversion is intentionally disabled.');
    }

    if (is_dir($output)) {
        $marker = $output . DIRECTORY_SEPARATOR . CONVERSION_MARKER;
        if (!$force) {
            fail("Output already exists: {$output}. Use --force only for a prior converter output.");
        }
        if (!is_file($marker)) {
            fail("Refusing to replace an unrecognized directory: {$output}");
        }
        removeDirectory($output);
    } elseif (file_exists($output)) {
        fail("Output exists and is not a directory: {$output}");
    }

    if (!mkdir($output, 0775, true) && !is_dir($output)) {
        fail("Unable to create output directory: {$output}");
    }

    file_put_contents($output . DIRECTORY_SEPARATOR . CONVERSION_MARKER, "Generated by " . basename(__FILE__) . "\n");
}

function copyExportAssets(string $source, string $output): void
{
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($source, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );

    foreach ($iterator as $item) {
        $relative = substr($item->getPathname(), strlen($source) + 1);
        if ($item->getFilename() === '.DS_Store' || preg_match('/\.html?$/i', $relative)) {
            continue;
        }

        $destination = $output . DIRECTORY_SEPARATOR . $relative;
        if ($item->isDir()) {
            if (!is_dir($destination) && !mkdir($destination, 0775, true) && !is_dir($destination)) {
                fail("Unable to create directory: {$destination}");
            }
            continue;
        }

        $parent = dirname($destination);
        if (!is_dir($parent) && !mkdir($parent, 0775, true) && !is_dir($parent)) {
            fail("Unable to create directory: {$parent}");
        }
        if (!copy($item->getPathname(), $destination)) {
            fail("Unable to copy: {$relative}");
        }
    }
}

function matchOne(string $pattern, string $html, string $label): array
{
    if (preg_match($pattern, $html, $matches, PREG_OFFSET_CAPTURE) !== 1) {
        fail("Could not find {$label}.");
    }
    return $matches;
}

function outerTag(string $html, string $tag, ?string $requiredAttribute = null): string
{
    $attribute = $requiredAttribute === null ? '' : '(?=[^>]*' . preg_quote($requiredAttribute, '~') . ')';
    $matches = matchOne("~<{$tag}\\b{$attribute}[^>]*>.*?</{$tag}>~is", $html, "<{$tag}> block");
    return $matches[0][0];
}

function innerTag(string $html, string $tag): string
{
    $matches = matchOne("~<{$tag}\\b[^>]*>(.*?)</{$tag}>~is", $html, "<{$tag}> block");
    return $matches[1][0];
}

function tagAttributes(string $html, string $tag): string
{
    $matches = matchOne("~<{$tag}\\b([^>]*)>~is", $html, "<{$tag}> opening tag");
    return $matches[1][0];
}

function attributeValue(string $attributes, string $name): string
{
    $quotedName = preg_quote($name, '~');
    if (preg_match("~\\b{$quotedName}\\s*=\\s*([\"'])(.*?)\\1~is", $attributes, $matches) === 1) {
        return html_entity_decode($matches[2], ENT_QUOTES | ENT_HTML5, 'UTF-8');
    }
    return '';
}

function metaContent(string $head, string $name): string
{
    if (preg_match_all('~<meta\\b[^>]*>~is', $head, $tags) !== false) {
        foreach ($tags[0] as $tag) {
            $attributes = tagAttributes($tag, 'meta');
            if (strcasecmp(attributeValue($attributes, 'name'), $name) === 0) {
                return attributeValue($attributes, 'content');
            }
        }
    }
    return '';
}

function titleContent(string $head): string
{
    if (preg_match('~<title\\b[^>]*>(.*?)</title>~is', $head, $matches) !== 1) {
        return '';
    }
    return html_entity_decode(trim(strip_tags($matches[1])), ENT_QUOTES | ENT_HTML5, 'UTF-8');
}

function customBlock(string $html, string $kind): string
{
    $kindQuoted = preg_quote($kind, '~');
    $pattern = "~<!--\\s*[^>]*Custom {$kindQuoted} Code\\s*-->(.*?)(?=<!--|$)~is";
    return preg_match($pattern, $html, $matches) === 1 ? trim($matches[1]) : '';
}

function withoutCustomBlock(string $html, string $kind): string
{
    $kindQuoted = preg_quote($kind, '~');
    return preg_replace("~\\s*<!--\\s*[^>]*Custom {$kindQuoted} Code\\s*-->.*?(?=\\s*<!--|$)~is", '', $html, 1) ?? $html;
}

function replaceHtmlLinks(string $html): string
{
    return preg_replace_callback(
        "~(href\\s*=\\s*[\"'])([^\"'?#]+)\\.html((?:[?#][^\"']*)?)([\"'])~i",
        static fn(array $m): string => $m[1] . $m[2] . '.php' . $m[3] . $m[4],
        $html
    ) ?? $html;
}

function normalSharedMarkup(string $html): string
{
    $html = preg_replace("~\\s+class=([\"'])active\\1~i", '', $html) ?? $html;
    $html = preg_replace("~\\s+active(?=[\"'])~i", '', $html) ?? $html;
    return preg_replace('~\\s+~', ' ', trim($html)) ?? trim($html);
}

function phpLiteral(string $value): string
{
    return var_export($value, true);
}

function nowdocAssignment(string $target, string $value, string $prefix): string
{
    if ($value === '') {
        return "{$target} = '';\n";
    }
    $marker = strtoupper($prefix) . '_' . substr(hash('sha256', $value), 0, 12);
    while (preg_match('/^' . preg_quote($marker, '/') . '$/m', $value) === 1) {
        $marker .= '_X';
    }
    return "{$target} = <<<'{$marker}'\n{$value}\n{$marker};\n";
}

function renderPage(array $page): string
{
    $definition = "<?php\n\n";
    $definition .= "declare(strict_types=1);\n\n";
    $definition .= "\$page = [\n";
    foreach (['slug', 'title', 'description', 'keywords', 'body_class'] as $key) {
        $definition .= "    " . phpLiteral($key) . ' => ' . phpLiteral($page[$key]) . ",\n";
    }
    $definition .= "];\n";
    $definition .= nowdocAssignment("\$page['head_extra']", $page['head_extra'], 'head_extra');
    $definition .= nowdocAssignment("\$page['body_extra']", $page['body_extra'], 'body_extra');
    $definition .= "\nrequire __DIR__ . '/includes/header.php';\n?>\n\n";
    $definition .= trim($page['main']) . "\n\n";
    $definition .= "<?php require __DIR__ . '/includes/footer.php'; ?>\n";
    return $definition;
}

function injectActiveNav(string $nav): string
{
    $nav = preg_replace("~\\s+active(?=[\"'])~i", '', $nav) ?? $nav;
    return preg_replace_callback(
        "~<a\\b([^>]*?)href=([\"'])([^\"']+\\.php)([^\"']*)\\2([^>]*)>~i",
        static function (array $m): string {
            $before = $m[1];
            $after = $m[5];
            $target = basename(parse_url($m[3], PHP_URL_PATH) ?: $m[3]);
            $attributes = $before . 'href=' . $m[2] . $m[3] . $m[4] . $m[2] . $after;
            if (preg_match("~class=([\"'])(.*?)\\1~is", $attributes) === 1) {
                $attributes = preg_replace(
                    "~class=([\"'])(.*?)\\1~is",
                    'class=$1$2<?= nav_active(' . phpLiteral($target) . ') ?>$1',
                    $attributes,
                    1
                ) ?? $attributes;
            } else {
                $attributes .= ' class="<?= trim(nav_active(' . phpLiteral($target) . ')) ?>"';
            }
            return '<a' . $attributes . '>';
        },
        $nav
    ) ?? $nav;
}

$options = getopt('', ['source:', 'output:', 'layout::', 'force', 'help']);
if (isset($options['help']) || !isset($options['source'], $options['output'])) {
    usage();
}

$source = canonicalPath((string) $options['source']);
$output = rtrim((string) $options['output'], DIRECTORY_SEPARATOR);
$layoutName = (string) ($options['layout'] ?? 'index.html');
$force = array_key_exists('force', $options);

if (!is_dir($source)) {
    fail("Source directory not found: {$source}");
}

$pages = glob($source . DIRECTORY_SEPARATOR . '*.html') ?: [];
sort($pages, SORT_NATURAL | SORT_FLAG_CASE);
if ($pages === []) {
    fail('No root-level .html pages were found in the export.');
}

$layoutPath = $source . DIRECTORY_SEPARATOR . $layoutName;
if (!is_file($layoutPath)) {
    fail("Layout page not found: {$layoutPath}");
}

$layoutHtml = file_get_contents($layoutPath);
if ($layoutHtml === false) {
    fail("Unable to read layout page: {$layoutPath}");
}

$layoutHead = innerTag($layoutHtml, 'head');
$layoutHeader = outerTag($layoutHtml, 'header');
$layoutNav = outerTag($layoutHeader, 'nav', 'id="navmenu"');
$layoutFooter = outerTag($layoutHtml, 'footer');

$navOffset = strpos($layoutHeader, $layoutNav);
if ($navOffset === false) {
    fail('Unable to split navigation from the shared header.');
}
$headerBeforeNav = substr($layoutHeader, 0, $navOffset);
$headerAfterNav = substr($layoutHeader, $navOffset + strlen($layoutNav));

$footerEnd = strpos($layoutHtml, $layoutFooter);
if ($footerEnd === false) {
    fail('Unable to locate shared footer position.');
}
$tailStart = $footerEnd + strlen($layoutFooter);
$bodyEnd = stripos($layoutHtml, '</body>', $tailStart);
if ($bodyEnd === false) {
    fail('Unable to find closing </body> tag.');
}
$layoutTail = substr($layoutHtml, $tailStart, $bodyEnd - $tailStart);
$sharedTail = withoutCustomBlock($layoutTail, 'Body');

$sharedHead = $layoutHead;
$sharedHead = preg_replace('~\\s*<title\\b[^>]*>.*?</title>~is', '', $sharedHead, 1) ?? $sharedHead;
$sharedHead = preg_replace('~\\s*<meta\\b[^>]*\\bcharset\\s*=\\s*[^>]+>~is', '', $sharedHead, 1) ?? $sharedHead;
$sharedHead = preg_replace("~\\s*<meta\\b(?=[^>]*\\bname=([\"'])viewport\\1)[^>]*>~is", '', $sharedHead, 1) ?? $sharedHead;
$sharedHead = preg_replace("~\\s*<meta\\b(?=[^>]*\\bname=([\"'])(?:description|keywords)\\1)[^>]*>~is", '', $sharedHead) ?? $sharedHead;
$sharedHead = withoutCustomBlock($sharedHead, 'Head');

prepareOutput($source, $output, $force);
copyExportAssets($source, $output);

$includes = $output . DIRECTORY_SEPARATOR . 'includes';
mkdir($includes, 0775, true);

$siteName = 'Website';
if (preg_match("~<[^>]+class=([\"'])[^\"']*\\bsitename\\b[^\"']*\\1[^>]*>(.*?)</[^>]+>~is", $layoutHeader, $siteMatch) === 1) {
    $siteName = trim(strip_tags($siteMatch[2]));
}

$config = "<?php\n\ndeclare(strict_types=1);\n\n";
$config .= "\$site = [\n    'name' => " . phpLiteral($siteName) . ",\n    'base_url' => '',\n];\n\n";
$config .= <<<'PHP'
function e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function nav_active(string $target): string
{
    global $page;
    $current = $page['slug'] ?? basename($_SERVER['SCRIPT_NAME'] ?? '');
    return basename($current) === basename($target) ? ' active' : '';
}
PHP;
$config .= "\n";
file_put_contents($includes . '/config.php', $config);

$nav = replaceHtmlLinks($layoutNav);
$nav = injectActiveNav($nav);
file_put_contents($includes . '/nav.php', "<?php\n\ndeclare(strict_types=1);\n?>\n" . trim($nav) . "\n");

$headerTemplate = "<?php\n\ndeclare(strict_types=1);\nrequire_once __DIR__ . '/config.php';\n\n";
$headerTemplate .= "\$page = array_merge([\n    'slug' => basename(\$_SERVER['SCRIPT_NAME'] ?? 'index.php'),\n    'title' => \$site['name'],\n    'description' => '',\n    'keywords' => '',\n    'body_class' => '',\n    'head_extra' => '',\n    'body_extra' => '',\n], \$page ?? []);\n?>\n";
$headerTemplate .= "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n";
$headerTemplate .= "  <meta charset=\"utf-8\">\n  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n";
$headerTemplate .= "  <title><?= e(\$page['title']) ?></title>\n";
$headerTemplate .= "  <?php if (\$page['description'] !== ''): ?><meta name=\"description\" content=\"<?= e(\$page['description']) ?>\"><?php endif; ?>\n";
$headerTemplate .= "  <?php if (\$page['keywords'] !== ''): ?><meta name=\"keywords\" content=\"<?= e(\$page['keywords']) ?>\"><?php endif; ?>\n";
$headerTemplate .= trim(replaceHtmlLinks($sharedHead)) . "\n";
$headerTemplate .= "  <?= \$page['head_extra'] ?>\n</head>\n\n<body class=\"<?= e(\$page['body_class']) ?>\">\n\n";
$headerTemplate .= trim(replaceHtmlLinks($headerBeforeNav)) . "\n";
$headerTemplate .= "<?php require __DIR__ . '/nav.php'; ?>\n";
$headerTemplate .= trim(replaceHtmlLinks($headerAfterNav)) . "\n";
file_put_contents($includes . '/header.php', $headerTemplate);

$footerTemplate = "<?php\n\ndeclare(strict_types=1);\n?>\n";
$footerTemplate .= trim(replaceHtmlLinks($layoutFooter)) . "\n";
$footerTemplate .= trim(replaceHtmlLinks($sharedTail)) . "\n";
$footerTemplate .= "<?= \$page['body_extra'] ?>\n\n</body>\n</html>\n";
file_put_contents($includes . '/footer.php', $footerTemplate);

$warnings = [];
foreach ($pages as $pagePath) {
    $html = file_get_contents($pagePath);
    if ($html === false) {
        fail("Unable to read page: {$pagePath}");
    }

    $name = basename($pagePath);
    $head = innerTag($html, 'head');
    $header = outerTag($html, 'header');
    $footer = outerTag($html, 'footer');
    $main = outerTag($html, 'main');
    $bodyAttributes = tagAttributes($html, 'body');

    if (normalSharedMarkup($header) !== normalSharedMarkup($layoutHeader)) {
        $warnings[] = "{$name}: header differs from {$layoutName}; shared layout uses {$layoutName}.";
    }
    if (normalSharedMarkup($footer) !== normalSharedMarkup($layoutFooter)) {
        $warnings[] = "{$name}: footer differs from {$layoutName}; shared layout uses {$layoutName}.";
    }

    $pageFooterPosition = strpos($html, $footer);
    if ($pageFooterPosition === false) {
        fail("Unable to locate footer position in {$name}.");
    }
    $pageTailStart = $pageFooterPosition + strlen($footer);
    $pageBodyEnd = stripos($html, '</body>', $pageTailStart);
    if ($pageBodyEnd === false) {
        fail("Unable to find closing </body> in {$name}.");
    }
    $pageTail = substr($html, $pageTailStart, $pageBodyEnd - $pageTailStart);

    $phpName = preg_replace('/\\.html$/i', '.php', $name) ?? $name . '.php';
    $page = [
        'slug' => $phpName,
        'title' => titleContent($head),
        'description' => metaContent($head, 'description'),
        'keywords' => metaContent($head, 'keywords'),
        'body_class' => attributeValue($bodyAttributes, 'class'),
        'head_extra' => replaceHtmlLinks(customBlock($head, 'Head')),
        'body_extra' => replaceHtmlLinks(customBlock($pageTail, 'Body')),
        'main' => replaceHtmlLinks($main),
    ];

    file_put_contents($output . DIRECTORY_SEPARATOR . $phpName, renderPage($page));
}

echo 'Converted ' . count($pages) . " pages to {$output}\n";
echo "Shared includes: includes/config.php, header.php, nav.php, footer.php\n";
if ($warnings !== []) {
    fwrite(STDERR, "Warnings:\n- " . implode("\n- ", $warnings) . "\n");
}
