#!/usr/bin/env php
<?php

declare(strict_types=1);

const CONVERSION_MARKER = '.bootstrapmade-php-conversion';

function fail(string $message, int $code = 1): never
{
    fwrite(STDERR, "Error: {$message}\n");
    exit($code);
}

function usage(): never
{
    $script = basename(__FILE__);
    fwrite(STDERR, <<<TEXT
Usage:
  php scripts/{$script} --source=/path/to/export --output=/path/to/php-site [--assets-from=/path/to/existing/assets] [--layout=index.html] [--force]

Options:
  --source   BootstrapMade export directory containing HTML pages.
  --output   New directory for the converted PHP site. It must differ from source.
  --assets-from  Existing assets directory to preserve before exported assets are layered over it.
  --layout   Page used as the shared header/nav/footer template (default: index.html).
  --force    Replace a prior output created by this converter.

TEXT);
    exit(2);
}

function canonicalPath(string $path): string
{
    $resolved = realpath($path);
    return $resolved !== false ? rtrim($resolved, DIRECTORY_SEPARATOR) : rtrim($path, DIRECTORY_SEPARATOR);
}

function removeDirectory(string $directory): void
{
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );

    foreach ($iterator as $item) {
        $path = $item->getPathname();
        $item->isDir() ? rmdir($path) : unlink($path);
    }

    rmdir($directory);
}

function prepareOutput(string $source, string $output, bool $force): void
{
    if (canonicalPath($source) === canonicalPath($output)) {
        fail('Source and output must be different directories. In-place conversion is intentionally disabled.');
    }

    if (is_dir($output)) {
        $marker = $output . DIRECTORY_SEPARATOR . CONVERSION_MARKER;
        if (!$force) {
            fail("Output already exists: {$output}. Use --force only for a prior converter output.");
        }
        if (!is_file($marker)) {
            fail("Refusing to replace an unrecognized directory: {$output}");
        }
        removeDirectory($output);
    } elseif (file_exists($output)) {
        fail("Output exists and is not a directory: {$output}");
    }

    if (!mkdir($output, 0775, true) && !is_dir($output)) {
        fail("Unable to create output directory: {$output}");
    }

    file_put_contents($output . DIRECTORY_SEPARATOR . CONVERSION_MARKER, "Generated by " . basename(__FILE__) . "\n");
}

function copyExportAssets(string $source, string $output): void
{
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($source, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );

    foreach ($iterator as $item) {
        $relative = substr($item->getPathname(), strlen($source) + 1);
        if (
            $item->getFilename() === '.DS_Store'
            || strcasecmp($item->getFilename(), 'Readme.txt') === 0
            || preg_match('/\.html?$/i', $relative)
        ) {
            continue;
        }

        $destination = $output . DIRECTORY_SEPARATOR . $relative;
        if ($item->isDir()) {
            if (!is_dir($destination) && !mkdir($destination, 0775, true) && !is_dir($destination)) {
                fail("Unable to create directory: {$destination}");
            }
            continue;
        }

        $parent = dirname($destination);
        if (!is_dir($parent) && !mkdir($parent, 0775, true) && !is_dir($parent)) {
            fail("Unable to create directory: {$parent}");
        }
        if (!copy($item->getPathname(), $destination)) {
            fail("Unable to copy: {$relative}");
        }
    }
}

function copyPreservedAssets(string $source, string $destination): void
{
    if (!is_dir($destination) && !mkdir($destination, 0775, true) && !is_dir($destination)) {
        fail("Unable to create preserved assets directory: {$destination}");
    }

    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($source, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );

    foreach ($iterator as $item) {
        if ($item->getFilename() === '.DS_Store') {
            continue;
        }

        $relative = substr($item->getPathname(), strlen($source) + 1);
        $target = $destination . DIRECTORY_SEPARATOR . $relative;
        if ($item->isDir()) {
            if (!is_dir($target) && !mkdir($target, 0775, true) && !is_dir($target)) {
                fail("Unable to create preserved asset directory: {$target}");
            }
            continue;
        }

        $parent = dirname($target);
        if (!is_dir($parent) && !mkdir($parent, 0775, true) && !is_dir($parent)) {
            fail("Unable to create preserved asset directory: {$parent}");
        }
        if (!copy($item->getPathname(), $target)) {
            fail("Unable to preserve asset: {$relative}");
        }
    }
}

function matchOne(string $pattern, string $html, string $label): array
{
    if (preg_match($pattern, $html, $matches, PREG_OFFSET_CAPTURE) !== 1) {
        fail("Could not find {$label}.");
    }
    return $matches;
}

function outerTag(string $html, string $tag, ?string $requiredAttribute = null): string
{
    $attribute = $requiredAttribute === null ? '' : '(?=[^>]*' . preg_quote($requiredAttribute, '~') . ')';
    $matches = matchOne("~<{$tag}\\b{$attribute}[^>]*>.*?</{$tag}>~is", $html, "<{$tag}> block");
    return $matches[0][0];
}

function innerTag(string $html, string $tag): string
{
    $matches = matchOne("~<{$tag}\\b[^>]*>(.*?)</{$tag}>~is", $html, "<{$tag}> block");
    return $matches[1][0];
}

function tagAttributes(string $html, string $tag): string
{
    $matches = matchOne("~<{$tag}\\b([^>]*)>~is", $html, "<{$tag}> opening tag");
    return $matches[1][0];
}

function attributeValue(string $attributes, string $name): string
{
    $quotedName = preg_quote($name, '~');
    if (preg_match("~\\b{$quotedName}\\s*=\\s*([\"'])(.*?)\\1~is", $attributes, $matches) === 1) {
        return html_entity_decode($matches[2], ENT_QUOTES | ENT_HTML5, 'UTF-8');
    }
    return '';
}

function metaContent(string $head, string $name): string
{
    if (preg_match_all('~<meta\\b[^>]*>~is', $head, $tags) !== false) {
        foreach ($tags[0] as $tag) {
            $attributes = tagAttributes($tag, 'meta');
            if (strcasecmp(attributeValue($attributes, 'name'), $name) === 0) {
                return attributeValue($attributes, 'content');
            }
        }
    }
    return '';
}

function titleContent(string $head): string
{
    if (preg_match('~<title\\b[^>]*>(.*?)</title>~is', $head, $matches) !== 1) {
        return '';
    }
    return html_entity_decode(trim(strip_tags($matches[1])), ENT_QUOTES | ENT_HTML5, 'UTF-8');
}

function customBlock(string $html, string $kind): string
{
    $kindQuoted = preg_quote($kind, '~');
    $pattern = "~<!--\\s*[^>]*Custom {$kindQuoted} Code\\s*-->(.*?)(?=<!--|$)~is";
    return preg_match($pattern, $html, $matches) === 1 ? trim($matches[1]) : '';
}

function withoutCustomBlock(string $html, string $kind): string
{
    $kindQuoted = preg_quote($kind, '~');
    return preg_replace("~\\s*<!--\\s*[^>]*Custom {$kindQuoted} Code\\s*-->.*?(?=\\s*<!--|$)~is", '', $html, 1) ?? $html;
}

function replaceHtmlLinks(string $html): string
{
    $html = preg_replace_callback(
        "~(href\\s*=\\s*[\"'])([^\"'?#]+)\\.html((?:[?#][^\"']*)?)([\"'])~i",
        static fn(array $m): string => $m[1] . $m[2] . '.php' . $m[3] . $m[4],
        $html
    ) ?? $html;

    return replaceStockImagePaths($html);
}

function replaceStockImagePaths(string $html): string
{
    return strtr($html, [
        'assets/img/health/cardiology-2.webp' => 'assets/img/services/plumbing.webp',
        'assets/img/health/cardiology-3.webp' => 'assets/img/services/plumbing.webp',
        'assets/img/health/neurology-3.webp' => 'assets/img/services/water.webp',
        'assets/img/health/orthopedics-1.webp' => 'assets/img/services/lighting.webp',
        'assets/img/health/orthopedics-4.webp' => 'assets/img/services/lighting.webp',
        'assets/img/health/pediatrics-2.webp' => 'assets/img/services/security.webp',
        'assets/img/health/pediatrics-4.webp' => 'assets/img/services/security.webp',
        'assets/img/health/oncology-2.webp' => 'assets/img/services/doors.webp',
        'assets/img/health/laboratory-3.webp' => 'assets/img/services/drywall.webp',
        'assets/img/health/emergency-3.webp' => 'assets/img/services/exterior.webp',
        'assets/img/health/emergency-4.webp' => 'assets/img/services/toolkit.webp',
        'assets/img/health/facilities-3.webp' => 'assets/img/brand/sun-city-home-exterior.webp',
        'assets/img/health/facilities-6.webp' => 'assets/img/services/visit.webp',
        'assets/img/health/consultation-3.webp' => 'assets/img/services/inspection.webp',
        'assets/img/health/surgery-2.webp' => 'assets/img/services/toolkit.webp',
        'assets/img/health/showcase-7.webp' => 'assets/img/brand/sun-city-home-exterior.webp',
        'assets/img/health/showcase-11.webp' => 'assets/img/services/visit.webp',
        'assets/img/health/showcase-1.webp' => 'assets/img/services/lighting.webp',
        'assets/img/health/showcase-5.webp' => 'assets/img/services/exterior.webp',
        'assets/img/health/staff-1.webp' => 'assets/img/services/plumbing.webp',
        'assets/img/health/staff-2.webp' => 'assets/img/services/grab-bars.webp',
        'assets/img/health/staff-3.webp' => 'assets/img/services/water.webp',
        'assets/img/health/staff-4.webp' => 'assets/img/services/drywall.webp',
        'assets/img/health/staff-5.webp' => 'assets/img/services/lighting.webp',
        'assets/img/health/staff-6.webp' => 'assets/img/services/inspection.webp',
        'assets/img/health/staff-7.webp' => 'assets/img/services/security.webp',
        'assets/img/health/staff-9.webp' => 'assets/img/services/doors.webp',
        'assets/img/health/staff-10.webp' => 'assets/img/services/exterior.webp',
        'assets/img/health/staff-11.webp' => 'assets/img/services/mounting.webp',
        'assets/img/health/staff-12.webp' => 'assets/img/services/toolkit.webp',
        'assets/img/person/person-f-3.webp' => 'assets/img/services/inspection.webp',
        'assets/img/person/person-m-9.webp' => 'assets/img/services/toolkit.webp',
        'assets/img/person/person-f-5.webp' => 'assets/img/services/doors.webp',
        'assets/img/person/person-f-12.webp' => 'assets/img/services/mounting.webp',
        'assets/img/person/person-m-12.webp' => 'assets/img/services/exterior.webp',
        'assets/img/person/person-m-13.webp' => 'assets/img/services/lighting.webp',
        'assets/img/person/person-f-13.webp' => 'assets/img/services/inspection.webp',
        'assets/img/gallery/gallery-1.webp' => 'assets/img/services/plumbing.webp',
        'assets/img/gallery/gallery-2.webp' => 'assets/img/services/lighting.webp',
        'assets/img/gallery/gallery-3.webp' => 'assets/img/services/security.webp',
        'assets/img/gallery/gallery-4.webp' => 'assets/img/services/doors.webp',
        'assets/img/gallery/gallery-5.webp' => 'assets/img/services/drywall.webp',
        'assets/img/gallery/gallery-6.webp' => 'assets/img/services/toolkit.webp',
        'assets/img/gallery/gallery-7.webp' => 'assets/img/services/exterior.webp',
        'assets/img/gallery/gallery-8.webp' => 'assets/img/services/visit.webp',
        'assets/img/clients/clients-6.webp' => 'assets/img/service-icons/client-location.svg',
        'assets/img/clients/clients-7.webp' => 'assets/img/service-icons/clear-scope.svg',
        'assets/img/clients/clients-8.webp' => 'assets/img/service-icons/practical-repairs.svg',
        'assets/img/clients/clients-9.webp' => 'assets/img/service-icons/project-details.svg',
        'assets/img/clients/clients-10.webp' => 'assets/img/service-icons/requirements-check.svg',
        'assets/img/clients/clients-11.webp' => 'assets/img/service-icons/right-sized-visits.svg',
    ]);
}

function normalSharedMarkup(string $html): string
{
    $html = preg_replace("~\\s+class=([\"'])active\\1~i", '', $html) ?? $html;
    $html = preg_replace("~\\s+active(?=[\"'])~i", '', $html) ?? $html;
    return preg_replace('~\\s+~', ' ', trim($html)) ?? trim($html);
}

function phpLiteral(string $value): string
{
    return var_export($value, true);
}

function defaultConfigContents(): string
{
    return <<<'PHP'
<?php
declare(strict_types=1);

const SITE_NAME = "Mark's Services";
const BUSINESS_NAME = "Mark's Services";
const BUSINESS_EMAIL = "office@marksservices.com";
const BUSINESS_PHONE_DISPLAY = "(512) 549-0322";
const BUSINESS_PHONE_TEL = "+15125490322";
const BUSINESS_CITY = "Georgetown";
const BUSINESS_STATE = "TX";
const BUSINESS_ZIP = "78633";
const BUSINESS_AREA = "Sun City & Berry Creek, Georgetown, Texas";
const BUSINESS_AREA_DETAIL =
    "Sun City, Georgetown, Williamson County 78633; Berry Creek, Georgetown, Williamson County 78628; and Georgetown 78626 and 78627";
const BUSINESS_ADDRESS_DISPLAY =
    "Client-location service in " . BUSINESS_AREA_DETAIL;
const BUSINESS_SERVICE_NOTE =
    "Client-location service in Sun City, Georgetown 78633 and Berry Creek, Georgetown 78628, Williamson County.";
const ELECTRICAL_LICENSE = "TECL 20547";
const ELECTRICAL_LICENSE_HOLDER = "Larry Kizer";
const PLUMBING_LICENSE = "M-38601";
const PLUMBING_LICENSE_HOLDER = "James Pote (Jim) Bradford";
const HANDYMAN_EXPERT = "Mark Walbert";
const HANDYMAN_EXPERIENCE = "25+ years";
const HANDYMAN_PRIOR_TRADE_EXPERIENCE =
    "20 years previously licensed in electrical and plumbing; those licenses are expired";

function e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");
}

function url_for(string $path): string
{
    return $path;
}

function is_active(string $current, array|string $targets): string
{
    return in_array($current, (array) $targets, true) ? "active" : "";
}

function site_base_url(): string
{
    $host = $_SERVER["HTTP_HOST"] ?? "www.marksservices.com";
    $https = $_SERVER["HTTPS"] ?? "";
    $scheme = $https !== "" && $https !== "off" ? "https" : "http";
    $script = $_SERVER["SCRIPT_NAME"] ?? "/index.php";
    $basePath = rtrim(str_replace("\\", "/", dirname($script)), "/");
    return $scheme . "://" . $host . ($basePath === "." ? "" : $basePath);
}

function absolute_url(string $path = ""): string
{
    $path = ltrim($path, "/");
    return rtrim(site_base_url(), "/") . ($path === "" ? "/" : "/" . $path);
}

function page_url(string $pageKey): string
{
    return absolute_url($pageKey === "index.php" ? "" : $pageKey);
}
PHP;
}

function nowdocAssignment(string $target, string $value, string $prefix): string
{
    if ($value === '') {
        return "{$target} = '';\n";
    }
    $marker = strtoupper($prefix) . '_' . substr(hash('sha256', $value), 0, 12);
    while (preg_match('/^' . preg_quote($marker, '/') . '$/m', $value) === 1) {
        $marker .= '_X';
    }
    return "{$target} = <<<'{$marker}'\n{$value}\n{$marker};\n";
}

function renderPage(string $pageKey, string $main): string
{
    $definition = "<?php\n\n";
    $definition .= "declare(strict_types=1);\n\n";
    $definition .= "\$pageKey = " . phpLiteral($pageKey) . ";\n";
    $definition .= "require __DIR__ . '/includes/header.php';\n?>\n\n";
    $definition .= trim($main) . "\n\n";
    $definition .= "<?php require __DIR__ . '/includes/footer.php'; ?>\n";
    return $definition;
}

function injectActiveNav(string $nav): string
{
    $nav = preg_replace("~\\s+active(?=[\"'])~i", '', $nav) ?? $nav;
    return preg_replace_callback(
        "~<a\\b([^>]*?)href=([\"'])([^\"']+\\.php)([^\"']*)\\2([^>]*)>~i",
        static function (array $m): string {
            $before = $m[1];
            $after = $m[5];
            $target = basename(parse_url($m[3], PHP_URL_PATH) ?: $m[3]);
            $attributes = $before . 'href=' . $m[2] . $m[3] . $m[4] . $m[2] . $after;
            if (preg_match("~class=([\"'])(.*?)\\1~is", $attributes) === 1) {
                $attributes = preg_replace(
                    "~class=([\"'])(.*?)\\1~is",
                    'class=$1$2 <?= is_active($pageKey, ' . phpLiteral($target) . ') ?>$1',
                    $attributes,
                    1
                ) ?? $attributes;
            } else {
                $attributes .= ' class="<?= is_active($pageKey, ' . phpLiteral($target) . ') ?>"';
            }
            return '<a' . $attributes . '>';
        },
        $nav
    ) ?? $nav;
}

$options = getopt('', ['source:', 'output:', 'assets-from:', 'layout::', 'force', 'help']);
if (isset($options['help']) || !isset($options['source'], $options['output'])) {
    usage();
}

$source = canonicalPath((string) $options['source']);
$output = rtrim((string) $options['output'], DIRECTORY_SEPARATOR);
$assetsFrom = isset($options['assets-from']) ? canonicalPath((string) $options['assets-from']) : null;
$layoutName = (string) ($options['layout'] ?? 'index.html');
$force = array_key_exists('force', $options);

if (!is_dir($source)) {
    fail("Source directory not found: {$source}");
}
if ($assetsFrom !== null && !is_dir($assetsFrom)) {
    fail("Preserved assets directory not found: {$assetsFrom}");
}

$pages = glob($source . DIRECTORY_SEPARATOR . '*.html') ?: [];
sort($pages, SORT_NATURAL | SORT_FLAG_CASE);
if ($pages === []) {
    fail('No root-level .html pages were found in the export.');
}

$layoutPath = $source . DIRECTORY_SEPARATOR . $layoutName;
if (!is_file($layoutPath)) {
    fail("Layout page not found: {$layoutPath}");
}

$layoutHtml = file_get_contents($layoutPath);
if ($layoutHtml === false) {
    fail("Unable to read layout page: {$layoutPath}");
}

$exportNote = '';
$readmePath = $source . DIRECTORY_SEPARATOR . 'Readme.txt';
if (is_file($readmePath)) {
    $readme = file_get_contents($readmePath);
    if ($readme !== false) {
        $exportNote = trim(preg_replace('/\s+/', ' ', $readme) ?? $readme);
    }
}

$layoutHead = innerTag($layoutHtml, 'head');
$layoutHeader = outerTag($layoutHtml, 'header');
$layoutHeader = preg_replace(
    '~(<header\b[^>]*\bclass=(["\'][^"\']*))\bposition-relative\b~i',
    '$1fixed-top',
    $layoutHeader,
    1
) ?? $layoutHeader;
$layoutNav = outerTag($layoutHeader, 'nav', 'id="navmenu"');
$layoutFooter = outerTag($layoutHtml, 'footer');

$navOffset = strpos($layoutHeader, $layoutNav);
if ($navOffset === false) {
    fail('Unable to split navigation from the shared header.');
}
$headerBeforeNav = substr($layoutHeader, 0, $navOffset);
$headerAfterNav = substr($layoutHeader, $navOffset + strlen($layoutNav));

$footerEnd = strpos($layoutHtml, $layoutFooter);
if ($footerEnd === false) {
    fail('Unable to locate shared footer position.');
}
$tailStart = $footerEnd + strlen($layoutFooter);
$bodyEnd = stripos($layoutHtml, '</body>', $tailStart);
if ($bodyEnd === false) {
    fail('Unable to find closing </body> tag.');
}
$layoutTail = substr($layoutHtml, $tailStart, $bodyEnd - $tailStart);
$sharedTail = withoutCustomBlock($layoutTail, 'Body');

$sharedHead = $layoutHead;
$sharedHead = preg_replace('~\\s*<title\\b[^>]*>.*?</title>~is', '', $sharedHead, 1) ?? $sharedHead;
$sharedHead = preg_replace('~\\s*<meta\\b[^>]*\\bcharset\\s*=\\s*[^>]+>~is', '', $sharedHead, 1) ?? $sharedHead;
$sharedHead = preg_replace("~\\s*<meta\\b(?=[^>]*\\bname=([\"'])viewport\\1)[^>]*>~is", '', $sharedHead, 1) ?? $sharedHead;
$sharedHead = preg_replace("~\\s*<meta\\b(?=[^>]*\\bname=([\"'])(?:description|keywords)\\1)[^>]*>~is", '', $sharedHead) ?? $sharedHead;
$sharedHead = withoutCustomBlock($sharedHead, 'Head');

prepareOutput($source, $output, $force);
if ($assetsFrom !== null) {
    copyPreservedAssets($assetsFrom, $output . DIRECTORY_SEPARATOR . 'assets');
}
copyExportAssets($source, $output);

$includes = $output . DIRECTORY_SEPARATOR . 'includes';
if (!is_dir($includes) && !mkdir($includes, 0775, true) && !is_dir($includes)) {
    fail("Unable to create includes directory: {$includes}");
}

$repositoryConfig = dirname(__DIR__) . '/includes/config.php';
$outputConfig = $includes . '/config.php';
if (is_file($repositoryConfig)) {
    if (!copy($repositoryConfig, $outputConfig)) {
        fail("Unable to preserve repository config: {$repositoryConfig}");
    }
} else {
    file_put_contents($outputConfig, defaultConfigContents() . "\n");
}

$repositoryPages = dirname(__DIR__) . '/includes/pages.php';
$outputPages = $includes . '/pages.php';
$preserveRepositoryPages = is_file($repositoryPages);
if ($preserveRepositoryPages && !copy($repositoryPages, $outputPages)) {
    fail("Unable to preserve repository page registry: {$repositoryPages}");
}

$repositoryServices = dirname(__DIR__) . '/includes/services.php';
$outputServices = $includes . '/services.php';
if (is_file($repositoryServices) && !copy($repositoryServices, $outputServices)) {
    fail("Unable to preserve repository service registry: {$repositoryServices}");
}

$nav = replaceHtmlLinks($layoutNav);
$nav = injectActiveNav($nav);
file_put_contents($includes . '/nav.php', "<?php\n\ndeclare(strict_types=1);\n?>\n" . trim($nav) . "\n");

$headerTemplate = "<?php\n\ndeclare(strict_types=1);\nrequire_once __DIR__ . '/config.php';\n\n";
$headerTemplate .= "\$pages = require __DIR__ . '/pages.php';\n\$pageKey = \$pageKey ?? 'index.php';\n\$page = \$pages[\$pageKey] ?? \$pages['index.php'] ?? [\n    'title' => SITE_NAME,\n    'description' => '',\n    'keywords' => '',\n    'body_class' => '',\n    'label' => SITE_NAME,\n];\n?>\n";
$headerTemplate .= "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n";
$headerTemplate .= "  <meta charset=\"utf-8\">\n  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n";
$headerTemplate .= "  <title><?= e(\$page['title']) ?></title>\n";
$headerTemplate .= "  <meta name=\"description\" content=\"<?= e(\$page['description']) ?>\">\n";
$headerTemplate .= "  <meta name=\"keywords\" content=\"<?= e(\$page['keywords']) ?>\">\n";
$headerTemplate .= "  <link rel=\"canonical\" href=\"<?= e(page_url(\$pageKey)) ?>\">\n";
$headerTemplate .= "  <meta property=\"og:site_name\" content=\"<?= e(SITE_NAME) ?>\">\n";
$headerTemplate .= "  <meta property=\"og:title\" content=\"<?= e(\$page['title']) ?>\">\n";
$headerTemplate .= "  <meta property=\"og:description\" content=\"<?= e(\$page['description']) ?>\">\n";
$headerTemplate .= "  <meta property=\"og:type\" content=\"website\">\n";
$headerTemplate .= "  <meta property=\"og:url\" content=\"<?= e(page_url(\$pageKey)) ?>\">\n";
$headerTemplate .= "  <meta name=\"twitter:card\" content=\"summary_large_image\">\n";
$headerTemplate .= "  <?php if (function_exists('structured_data_for_page')): ?>\n  <script type=\"application/ld+json\">\n<?= json_encode(structured_data_for_page(\$pageKey, \$page), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>\n  </script>\n  <?php endif; ?>\n";
$headerTemplate .= trim(replaceHtmlLinks($sharedHead)) . "\n";
$headerTemplate .= "</head>\n\n<body class=\"<?= e(\$page['body_class']) ?>\">\n\n";
$headerTemplate .= trim(replaceHtmlLinks($headerBeforeNav)) . "\n";
$headerTemplate .= "<?php require __DIR__ . '/nav.php'; ?>\n";
$headerTemplate .= trim(replaceHtmlLinks($headerAfterNav)) . "\n";
file_put_contents($includes . '/header.php', $headerTemplate);

$footerTemplate = "<?php\n\ndeclare(strict_types=1);\n?>\n";
$footerTemplate .= trim(replaceHtmlLinks($layoutFooter)) . "\n";
$footerTemplate .= trim(replaceHtmlLinks($sharedTail)) . "\n";
$footerTemplate .= "</body>\n</html>\n";
file_put_contents($includes . '/footer.php', $footerTemplate);

$warnings = [];
$generatedPageRegistry = [];
foreach ($pages as $pagePath) {
    $html = file_get_contents($pagePath);
    if ($html === false) {
        fail("Unable to read page: {$pagePath}");
    }

    $name = basename($pagePath);
    $head = innerTag($html, 'head');
    $header = outerTag($html, 'header');
    $footer = outerTag($html, 'footer');
    $main = outerTag($html, 'main');
    $bodyAttributes = tagAttributes($html, 'body');

    if (normalSharedMarkup($header) !== normalSharedMarkup($layoutHeader)) {
        $warnings[] = "{$name}: header differs from {$layoutName}; shared layout uses {$layoutName}.";
    }
    if (normalSharedMarkup($footer) !== normalSharedMarkup($layoutFooter)) {
        $warnings[] = "{$name}: footer differs from {$layoutName}; shared layout uses {$layoutName}.";
    }

    $phpName = preg_replace('/\\.html$/i', '.php', $name) ?? $name . '.php';
    $label = $phpName === '404.php'
        ? '404'
        : ucwords(str_replace(['-', '_'], ' ', pathinfo($phpName, PATHINFO_FILENAME)));
    $generatedPageRegistry[$phpName] = [
        'title' => titleContent($head),
        'description' => metaContent($head, 'description'),
        'keywords' => metaContent($head, 'keywords'),
        'body_class' => attributeValue($bodyAttributes, 'class'),
        'label' => $label,
    ];

    file_put_contents(
        $output . DIRECTORY_SEPARATOR . $phpName,
        renderPage($phpName, replaceHtmlLinks($main))
    );
}

if (!$preserveRepositoryPages) {
    $pagesFile = "<?php\n\ndeclare(strict_types=1);\n\nreturn " . var_export($generatedPageRegistry, true) . ";\n";
    file_put_contents($outputPages, $pagesFile);
}

echo 'Converted ' . count($pages) . " pages to {$output}\n";
echo "Shared includes: includes/config.php, pages.php, services.php, header.php, nav.php, footer.php\n";
if ($exportNote !== '') {
    echo "Suggested commit note: {$exportNote}\n";
}
if ($warnings !== []) {
    fwrite(STDERR, "Warnings:\n- " . implode("\n- ", $warnings) . "\n");
}
