<?php

declare(strict_types=1);

/**
 * Authoritative service content registry.
 *
 * This file is intentionally independent from the current HTML templates. It can
 * later drive service cards, navigation, landing pages, internal links, FAQs,
 * OfferCatalog entries, and Service schema after the site is converted to PHP.
 */
return [
    "major_groups" => [
        ["label" => "Plumbing Fixture Repairs", "href" => "services.php#plumbing-fixtures"],
        ["label" => "Water Heaters & Filtration", "href" => "services.php#water-systems"],
        ["label" => "Electrical & Lighting", "href" => "services.php#electrical-lighting"],
        ["label" => "Security & Smart Home", "href" => "services.php#security-smart-home"],
        ["label" => "Doors & Small Carpentry", "href" => "services.php#doors-carpentry"],
        ["label" => "Wall Repairs & Punch Lists", "href" => "services.php#wall-repairs-maintenance"],
    ],
    "service_areas" => [
        "Sun City Texas 78633",
        "Berry Creek, Texas 78628",
        "Georgetown, Texas 78626",
        "Williamson County 78627",
    ],
    "scope_note" =>
        "Minor repairs, fixture installations, home maintenance, and punch-list work; licensed trades coordinated when required.",
    "url_pattern" => "/services/%s/",
    "conditional_services" => [
        "Breaker troubleshooting, whole-house surge protectors, EV chargers, water heaters, and other licensed-trade work require appropriately licensed coordination when applicable.",
        "Thermostat replacement and AC vent or register-cover repair exclude HVAC equipment, refrigerant, furnace, and ductwork service.",
        "Exterior-visible work may require HOA, permit, utility, and manufacturer review.",
        "Gas-related and fireplace-system work is not marketed without verified licensed scope and advance approval.",
    ],
    "excluded_services" => [
        "Deck building or deck repair as a primary service",
        "Fence building, fence replacement, or fence painting as a primary service",
        "Full interior or exterior painting",
        "Roofing or roof repair",
        "HVAC equipment, air-conditioning, furnace, or ductwork service",
        "Unverified gas work",
        "Full remodeling or large construction projects",
    ],
    "categories" => [
        "handyman" => [
            "label" => "Handyman Services in Sun City Georgetown",
            "services" => ["handyman-services-sun-city-georgetown"],
        ],
        "plumbing_fixtures" => [
            "label" => "Faucet, Sink, Toilet & Drain Repairs",
            "services" => ["faucet-sink-toilet-repair-georgetown-tx", "garbage-disposal-installation-georgetown-tx"],
        ],
        "water_systems" => [
            "label" => "Water Heater, Water Softener & Filter Services",
            "services" => ["water-heater-installation-georgetown-tx", "water-softener-installation-georgetown-tx"],
        ],
        "electrical_fixtures" => [
            "label" => "Light, Fan, Switch & Outlet Services",
            "services" => ["light-fan-switch-installation-georgetown-tx", "lighting-security-smart-home-georgetown-tx", "ev-charger-installation-georgetown-tx"],
        ],
        "doors" => [
            "label" => "Door, Lock & Hardware Services",
            "services" => ["door-lock-hardware-repair-georgetown-tx"],
        ],
        "carpentry" => [
            "label" => "Trim, Cabinet & Small Carpentry Repairs",
            "services" => ["cabinet-trim-carpentry-georgetown-tx"],
        ],
        "walls" => [
            "label" => "Drywall, Paint Touch-Up & Wall Repair",
            "services" => ["drywall-paint-touch-up-repair-georgetown-tx"],
        ],
        "home_safety" => [
            "label" => "Grab Bars, Towel Bars & Home Safety Installs",
            "services" => ["grab-bar-installation-sun-city-georgetown"],
        ],
        "exterior_maintenance" => [
            "label" => "Gutters, Fascia, Caulking & Minor Exterior Repairs",
            "services" => ["exterior-home-maintenance-georgetown-tx"],
        ],
        "home_prep" => [
            "label" => "Home Sale Punch Lists & Inspection Repairs",
            "services" => ["home-inspection-repairs-georgetown-tx", "home-sale-punch-list-georgetown-tx"],
        ],
    ],
    "services" => [
        "handyman-services-sun-city-georgetown" => [
            "slug" => "handyman-services-sun-city-georgetown",
            "short_title" => "Handyman & home maintenance",
            "title" => "Handyman Services in Sun City Georgetown, TX",
            "eyebrow" => "Practical help for the whole punch list",
            "meta_description" =>
                "Handyman repairs, maintenance, and small installations for Sun City and Georgetown homeowners, with licensed trades coordinated when required.",
            "intro" =>
                "Small repairs have a way of piling up. Sun City Home Repair helps homeowners work through practical maintenance, installation, and punch-list tasks without turning every item into a large project.",
            "summary" =>
                "From loose hardware and high-reach replacements to home-sale lists and everyday repairs, the work is scoped carefully, explained plainly, and completed at your home.",
            "icon" => "bi-tools",
            "featured" => true,
            "tasks" => [
                "General home repairs", "Home maintenance", "Small installations", "Household punch lists",
                "Curtain rod installation", "Mirror hanging", "Blind installation", "TV mounting", "Flag bracket installation",
                "High-reach light and smoke detector replacement", "Shower door installation",
                "AC vent or register-cover repair only; no HVAC equipment service",
            ],
            "details" => [
                ["name" => "Household punch lists", "description" => "Group several manageable repairs and installations into one clear visit plan."],
                ["name" => "Fixture and hardware installs", "description" => "Install shelves, blinds, curtain rods, mirrors, towel bars, door hardware, and similar items."],
                ["name" => "Home maintenance", "description" => "Address wear, sticking parts, loose trim, minor leaks, and other items that affect daily use."],
                ["name" => "High-reach tasks", "description" => "Replace accessible lights and smoke detectors without asking homeowners to climb ladders."],
                ["name" => "Move-in and move-out help", "description" => "Complete practical repairs from inspection notes or a homeowner-prepared list."],
                ["name" => "Licensed help when required", "description" => "Identify when plumbing or electrical work needs the right licensed professional."],
            ],
            "good_fit" => [
                "Several small repairs in different rooms",
                "A written home inspection or maintenance list",
                "Installations that need careful placement and secure mounting",
            ],
            "caution" => null,
            "faqs" => [
                ["question" => "Can I combine several small jobs in one request?", "answer" => "Yes. A clear list with photos helps group compatible tasks and identify materials before the visit."],
                ["question" => "What work is outside the handyman scope?", "answer" => "Large remodeling, roofing, HVAC equipment service, gas work, and major construction are not marketed. Licensed plumbing or electrical work is coordinated when required."],
                ["question" => "Do you work at the customer's home?", "answer" => "Yes. We come to homes in Sun City, Berry Creek, and the Georgetown area."],
            ],
            "service_types" => ["Handyman Services", "Home Maintenance", "Small Home Installations"],
            "related" => ["home-inspection-repairs-georgetown-tx", "home-sale-punch-list-georgetown-tx", "grab-bar-installation-sun-city-georgetown"],
        ],
        "faucet-sink-toilet-repair-georgetown-tx" => [
            "slug" => "faucet-sink-toilet-repair-georgetown-tx",
            "short_title" => "Faucet, sink, toilet & drain repairs",
            "title" => "Faucet, Sink, Toilet & Drain Repairs in Georgetown, TX",
            "eyebrow" => "Plumbing fixture help without guesswork",
            "meta_description" =>
                "Faucet, sink, toilet, drain, bidet, hose bib, and minor leak repairs for Sun City, Berry Creek, and Georgetown homeowners.",
            "intro" =>
                "A dripping faucet, slow sink, running toilet, or loose fixture can waste water and make a room harder to use. We troubleshoot the fixture, explain the likely repair, and keep the work focused on the problem at hand.",
            "summary" =>
                "Fixture services include repairs, replacements, adjustments, and careful coordination when the work requires a licensed plumber.",
            "icon" => "bi-droplet",
            "featured" => true,
            "tasks" => [
                "Faucet repair and replacement", "Kitchen faucet installation", "Bathroom faucet installation",
                "Sink repair and installation", "Undermount sink installation", "Mop or utility sink installation",
                "Pop-up drain repair", "Sink stopper repair", "Clogged sink repair", "Dishwasher installation",
                "Dishwasher drain-loop correction", "Ice maker water-line installation", "Toilet repair",
                "Toilet fill-valve and float replacement", "Toilet tank-kit replacement", "Toilet wax-ring replacement",
                "Bidet installation and leak repair", "Hose bib leak repair", "Minor plumbing leak repair",
            ],
            "details" => [
                ["name" => "Faucets and sinks", "description" => "Repair or replace kitchen and bath faucets, pop-up drains, stoppers, and accessible sink components."],
                ["name" => "Toilet repairs", "description" => "Address fill valves, floats, tank hardware, wax rings, leaks, and running or weak-flush symptoms."],
                ["name" => "Minor drain issues", "description" => "Troubleshoot slow or clogged sinks and correct accessible drain connections where appropriate."],
                ["name" => "Bidets and hose bibs", "description" => "Install or repair compatible bidet fixtures and address minor hose bib leaks."],
                ["name" => "Dishwasher connections", "description" => "Install compatible dishwashers and correct accessible drain-loop or supply connection issues."],
                ["name" => "Ice maker lines", "description" => "Install or troubleshoot accessible ice maker water lines within the approved scope."],
            ],
            "good_fit" => ["A fixture that drips, runs, rocks, or no longer operates correctly", "A planned fixture replacement", "An inspection note involving an accessible plumbing fixture"],
            "caution" => "Some repairs require shutoff, code, permit, or licensed-plumber review. We confirm the scope before work begins and coordinate licensed plumbing when required.",
            "faqs" => [
                ["question" => "Should I buy the replacement fixture first?", "answer" => "Photos and model information are helpful before purchasing. Confirming dimensions, connections, finish, and included parts can prevent a mismatched fixture."],
                ["question" => "Do you repair major water or sewer lines?", "answer" => "No. This page covers household fixtures, minor leaks, and accessible connections. Major piping, sewer, or structural water problems need a licensed specialist."],
            ],
            "service_types" => ["Plumbing Fixture Repair", "Faucet Repair and Replacement", "Sink Repair", "Toilet Repair"],
            "related" => ["garbage-disposal-installation-georgetown-tx", "water-heater-installation-georgetown-tx", "water-softener-installation-georgetown-tx"],
        ],
        "water-heater-installation-georgetown-tx" => [
            "slug" => "water-heater-installation-georgetown-tx",
            "short_title" => "Water heater service",
            "title" => "Water Heater Installation & Replacement in Georgetown, TX",
            "eyebrow" => "Thoughtful planning for dependable hot water",
            "meta_description" => "Water heater replacement, flushing, point-of-use units, and troubleshooting in Georgetown, with licensed plumbing coordinated when required.",
            "intro" => "Water heater work starts with understanding the existing unit, available space, utilities, venting, drainage, and household needs. We help organize the right path without overselling the project.",
            "summary" => "Service may include maintenance, replacement planning, point-of-use equipment, and licensed installation coordination based on the home and equipment.",
            "icon" => "bi-thermometer-half",
            "featured" => false,
            "tasks" => [
                "Water heater installation or replacement with licensed coordination when required",
                "Water heater flushing", "Point-of-use water heater installation", "Water-flow and temperature troubleshooting",
            ],
            "details" => [
                ["name" => "Replacement planning", "description" => "Review the existing equipment, connections, access, capacity, and likely replacement requirements."],
                ["name" => "Water heater flushing", "description" => "Perform appropriate maintenance when the equipment condition and manufacturer guidance support it."],
                ["name" => "Point-of-use heaters", "description" => "Evaluate compact hot-water options for compatible sinks or limited applications."],
                ["name" => "Flow and temperature checks", "description" => "Separate fixture behavior from equipment issues before recommending work."],
                ["name" => "Licensed installation", "description" => "Coordinate properly licensed plumbing or electrical work when the scope requires it."],
            ],
            "good_fit" => ["An aging or leaking water heater", "Long waits for hot water at a distant fixture", "A planned replacement that needs clear equipment and access review"],
            "caution" => "Water heater work may involve plumbing, electrical, venting, drainage, expansion control, permit, and manufacturer requirements. Licensed trades are coordinated when required; gas work is not offered without verified licensed scope.",
            "faqs" => [
                ["question" => "Can you tell me what size water heater I need?", "answer" => "Sizing depends on household demand, recovery rate, available utilities, space, and the existing installation. Those details should be reviewed before choosing equipment."],
                ["question" => "Do you service gas water heaters?", "answer" => "Gas work is not offered unless the exact scope and licensed coordination are verified in advance."],
            ],
            "service_types" => ["Water Heater Installation", "Water Heater Replacement", "Water Heater Maintenance"],
            "related" => ["water-softener-installation-georgetown-tx", "faucet-sink-toilet-repair-georgetown-tx"],
        ],
        "water-softener-installation-georgetown-tx" => [
            "slug" => "water-softener-installation-georgetown-tx",
            "short_title" => "Water softeners & filtration",
            "title" => "Water Softener & Filter Services in Georgetown, TX",
            "eyebrow" => "Better water starts with the right assessment",
            "meta_description" => "Water softener, whole-house filter, reverse osmosis, water-flow, and water-test assistance for Sun City and Georgetown homes.",
            "intro" => "Hard water, taste, odor, scale, or reduced flow can have different causes. We help homeowners review the signs, equipment, maintenance history, and water goals before choosing a solution.",
            "summary" => "Services cover compatible softeners, whole-house filters, reverse osmosis equipment, programming, maintenance, and water-flow troubleshooting.",
            "icon" => "bi-water",
            "featured" => true,
            "tasks" => [
                "Water softener installation", "Water softener programming", "Water softener troubleshooting",
                "Whole-house water-filter installation", "Reverse-osmosis filter installation",
                "Water-flow troubleshooting", "Water-test assistance",
            ],
            "details" => [
                ["name" => "Water softeners", "description" => "Install, program, maintain, or troubleshoot compatible residential water-softening equipment."],
                ["name" => "Whole-house filters", "description" => "Plan and install filtration equipment appropriate to the home's connections and service needs."],
                ["name" => "Reverse osmosis", "description" => "Install or service compatible under-sink drinking-water systems and replacement filters."],
                ["name" => "Water-flow troubleshooting", "description" => "Check accessible valves, filters, fixtures, and equipment settings that may affect flow."],
                ["name" => "Water-test assistance", "description" => "Help interpret homeowner test goals and organize appropriate next steps without making unsupported health claims."],
            ],
            "good_fit" => ["Scale or spotting linked to hard water", "Existing equipment that is not cycling or delivering expected results", "A homeowner comparing softening and filtration options"],
            "caution" => "Equipment selection should reflect actual water conditions, plumbing layout, drainage, pressure, manufacturer requirements, and any permit or licensed-trade needs.",
            "faqs" => [
                ["question" => "Is a water softener the same as a water filter?", "answer" => "No. Softeners primarily address hardness minerals, while filters target specific particles, tastes, odors, or contaminants based on the media and system design."],
                ["question" => "Can you help with an existing system?", "answer" => "Yes. Model information, photos, recent behavior, and maintenance history help determine whether programming, service, parts, or replacement should be considered."],
            ],
            "service_types" => ["Water Softener Installation", "Whole-House Water Filter Installation", "Reverse Osmosis Filter Installation"],
            "related" => ["water-heater-installation-georgetown-tx", "faucet-sink-toilet-repair-georgetown-tx"],
        ],
        "garbage-disposal-installation-georgetown-tx" => [
            "slug" => "garbage-disposal-installation-georgetown-tx",
            "short_title" => "Garbage disposal installation",
            "title" => "Garbage Disposal Installation in Georgetown, TX",
            "eyebrow" => "Clean, compatible kitchen fixture replacement",
            "meta_description" => "Garbage disposal replacement and installation for Sun City, Berry Creek, and Georgetown kitchens, with connection checks and clear scope.",
            "intro" => "A noisy, leaking, jammed, or failed disposal can interrupt the whole kitchen routine. We verify the sink connection, available space, drain arrangement, power, and switch setup before replacement.",
            "summary" => "The goal is a properly fitted unit, sound drain connection, and a clean test of normal operation—not a larger kitchen project.",
            "icon" => "bi-recycle",
            "featured" => false,
            "tasks" => [
                "Garbage disposal installation", "Garbage disposal replacement", "Disposal jam and operation checks",
                "Accessible disposal leak checks", "Dishwasher-to-disposal connection checks",
            ],
            "details" => [
                ["name" => "Disposal replacement", "description" => "Remove a failed compatible unit and install a correctly sized replacement."],
                ["name" => "Leak checks", "description" => "Inspect accessible flange, drain, dishwasher, and discharge connections for common leak points."],
                ["name" => "Jam and operation checks", "description" => "Determine whether a safe reset or clearing step is appropriate before replacement."],
                ["name" => "Dishwasher connection", "description" => "Confirm the dishwasher inlet and drain-loop arrangement when connected to the disposal."],
                ["name" => "Licensed coordination", "description" => "Coordinate electrical or plumbing work when the existing setup falls outside a straightforward fixture replacement."],
            ],
            "good_fit" => ["A disposal that hums, leaks, or no longer runs", "A planned like-for-like replacement", "A kitchen inspection item involving the disposal connection"],
            "caution" => "Hardwired changes, new circuits, damaged wiring, or material drain reconfiguration may require a licensed trade.",
            "faqs" => [
                ["question" => "Can I buy any disposal that fits the sink?", "answer" => "Compatibility also depends on cabinet space, mounting style, drain alignment, dishwasher connection, power, and switch arrangement. Review those details before purchasing."],
                ["question" => "Do you clear main kitchen drain lines?", "answer" => "This service covers the disposal and accessible fixture connections. Deeper or recurring drain problems may need a licensed drain specialist."],
            ],
            "service_types" => ["Garbage Disposal Installation", "Garbage Disposal Replacement"],
            "related" => ["faucet-sink-toilet-repair-georgetown-tx", "home-inspection-repairs-georgetown-tx"],
        ],
        "light-fan-switch-installation-georgetown-tx" => [
            "slug" => "light-fan-switch-installation-georgetown-tx",
            "short_title" => "Lights, fans, switches & outlets",
            "title" => "Light, Fan, Switch & Outlet Services in Georgetown, TX",
            "eyebrow" => "Small electrical improvements, carefully scoped",
            "meta_description" => "Light fixtures, ceiling fans, switches, dimmers, outlets, GFCIs, doorbells, and smoke detectors for Georgetown-area homes.",
            "intro" => "A fixture or device replacement should look right, operate correctly, and match the home's existing electrical conditions. We start with the visible setup and coordinate licensed electrical work when required.",
            "summary" => "Services include compatible fixture and device replacement, troubleshooting, and installation support for everyday residential needs.",
            "icon" => "bi-lightbulb",
            "featured" => true,
            "tasks" => [
                "Light fixture installation", "LED light replacement", "Pendant light installation", "Wall sconce installation",
                "Ceiling fan installation or replacement", "Bathroom fan or vent-related fixture repair",
                "Dimmer switch installation", "Light switch replacement", "Outlet replacement", "GFCI outlet replacement",
                "Breaker troubleshooting with licensed coordination as needed", "Doorbell installation and repair",
                "Smoke detector installation", "Whole-house surge-protector coordination when properly licensed",
                "Garage light installation", "TV or media outlet assistance", "Lamp rewiring",
                "Thermostat replacement where permitted; no HVAC system service",
            ],
            "details" => [
                ["name" => "Light fixtures", "description" => "Install compatible ceiling lights, pendants, sconces, garage lights, and LED replacements."],
                ["name" => "Ceiling fans", "description" => "Replace or install compatible fans where the mounting and electrical setup are suitable."],
                ["name" => "Switches and dimmers", "description" => "Replace worn or incompatible controls and verify fixture compatibility."],
                ["name" => "Outlets and GFCIs", "description" => "Address accessible device replacement and coordinate broader troubleshooting when needed."],
                ["name" => "Doorbells and detectors", "description" => "Install or replace compatible doorbells and smoke detectors within the approved scope."],
                ["name" => "Media and TV outlets", "description" => "Assist with accessible media connections and device placement."],
            ],
            "good_fit" => ["A dated or failed fixture", "A fan or light upgrade in an existing location", "A loose, worn, or nonworking switch or receptacle that needs evaluation"],
            "caution" => "Electrical code, box support, wiring condition, circuit capacity, permit, and manufacturer requirements may affect the scope. Licensed electrical work is coordinated when required.",
            "faqs" => [
                ["question" => "Can a ceiling fan replace any light fixture?", "answer" => "Not always. The box and support must be fan-rated, and the wiring and controls must suit the new fan."],
                ["question" => "Do you replace electrical panels or rewire homes?", "answer" => "No. This page covers fixtures and devices. Panel work, circuit additions, and significant wiring changes require a licensed electrical contractor."],
            ],
            "service_types" => ["Light Fixture Installation", "Ceiling Fan Installation", "Switch and Outlet Replacement", "GFCI Outlet Replacement"],
            "related" => ["lighting-security-smart-home-georgetown-tx", "ev-charger-installation-georgetown-tx"],
        ],
        "lighting-security-smart-home-georgetown-tx" => [
            "slug" => "lighting-security-smart-home-georgetown-tx",
            "short_title" => "Lighting, security & smart home",
            "title" => "Lighting, Security Camera & Smart Home Installation in Georgetown, TX",
            "eyebrow" => "Useful technology, installed with the home in mind",
            "meta_description" => "Video doorbells, security cameras, smart locks, lighting, smoke detectors, and smart panels for Sun City and Georgetown homes.",
            "intro" => "Smart devices work best when placement, Wi-Fi coverage, power, visibility, privacy, and everyday usability are considered together. We help homeowners choose a practical installation plan and keep exterior-visible changes in view.",
            "summary" => "Services include compatible video doorbells, cameras, locks, security panels, detectors, and lighting upgrades—not monitoring subscriptions or unsupported security guarantees.",
            "icon" => "bi-camera-video",
            "featured" => false,
            "tasks" => [
                "Video doorbell installation", "Security camera installation", "Smart lock installation",
                "Smart home security-panel mounting", "Smoke detector installation", "Safety and exterior lighting upgrades",
            ],
            "details" => [
                ["name" => "Video doorbells", "description" => "Install compatible wired or battery devices with attention to viewing angle, power, and app setup."],
                ["name" => "Security cameras", "description" => "Plan useful camera placement while limiting unnecessary exterior impact and blind spots."],
                ["name" => "Smart locks", "description" => "Install and align compatible locks, then assist with basic setup and operation."],
                ["name" => "Security panels", "description" => "Mount and configure compatible homeowner-provided smart home panels."],
                ["name" => "Safety and exterior lighting", "description" => "Replace or upgrade compatible fixtures with attention to glare, aiming, access, and controls."],
                ["name" => "Smoke detectors", "description" => "Replace accessible compatible detectors and help organize high-reach locations."],
            ],
            "good_fit" => ["A video doorbell or camera upgrade", "A smart lock that needs careful alignment", "Lighting that would be more useful with better placement or controls"],
            "caution" => "For exterior cameras, video doorbells, lighting, conduit, or visible work, confirm HOA, permit, utility, and manufacturer requirements. Electrical work is coordinated with a licensed trade when required.",
            "faqs" => [
                ["question" => "Can you guarantee complete camera coverage?", "answer" => "No system eliminates every blind spot or risk. We can help plan practical placement based on the home, device limits, privacy, power, and network coverage."],
                ["question" => "Do you provide security monitoring?", "answer" => "No. Installation and basic setup are separate from monitoring plans, subscriptions, cloud storage, or manufacturer support."],
            ],
            "service_types" => ["Video Doorbell Installation", "Security Camera Installation", "Smart Lock Installation", "Lighting Installation"],
            "related" => ["light-fan-switch-installation-georgetown-tx", "door-lock-hardware-repair-georgetown-tx", "ev-charger-installation-georgetown-tx"],
        ],
        "ev-charger-installation-georgetown-tx" => [
            "slug" => "ev-charger-installation-georgetown-tx",
            "short_title" => "EV charger coordination",
            "title" => "EV Charger Installation Coordination in Georgetown, TX",
            "eyebrow" => "A clear path from vehicle to garage power",
            "meta_description" => "Level 2 EV charger planning and licensed installation coordination for Sun City, Berry Creek, and Georgetown homeowners.",
            "intro" => "A home EV charger is more than a wall-mounted device. The vehicle, charger, parking position, cable reach, electrical capacity, utility requirements, and permit path all matter.",
            "summary" => "We help organize site review, device placement, and installation details, with properly licensed electrical work coordinated for the final connection.",
            "icon" => "bi-ev-station",
            "featured" => false,
            "tasks" => [
                "EV charger site planning", "Level 2 charger placement planning", "Cable-reach and parking-position review",
                "Permit and utility coordination", "Licensed electrical installation coordination",
            ],
            "details" => [
                ["name" => "Charger and vehicle review", "description" => "Confirm connector type, charging goals, manufacturer requirements, and likely circuit needs."],
                ["name" => "Garage placement", "description" => "Plan mounting height, cable reach, parking position, and protection from everyday garage activity."],
                ["name" => "Electrical capacity review", "description" => "Coordinate evaluation of panel capacity, circuit route, load considerations, and disconnect needs."],
                ["name" => "Permit and utility coordination", "description" => "Identify local steps that may apply before installation."],
                ["name" => "Licensed installation", "description" => "Coordinate the code-compliant electrical connection with an appropriately licensed contractor."],
            ],
            "good_fit" => ["A new EV arriving soon", "A homeowner comparing plug-in and hardwired Level 2 chargers", "A garage where cable routing and charger placement need planning"],
            "caution" => "Confirm HOA, permit, utility, manufacturer, and licensed-electrical requirements before installation. Exterior conduit or equipment may need additional review.",
            "faqs" => [
                ["question" => "Can you install a Level 2 charger on any electrical panel?", "answer" => "Not automatically. Available capacity, existing loads, panel condition, circuit route, charger settings, and local requirements must be reviewed by the appropriate licensed professional."],
                ["question" => "Should I buy the charger before the site review?", "answer" => "It is often better to compare the vehicle, charging goals, electrical options, cable length, and manufacturer requirements first."],
            ],
            "service_types" => ["EV Charger Coordination", "EV Station Installation Coordination"],
            "related" => ["light-fan-switch-installation-georgetown-tx", "lighting-security-smart-home-georgetown-tx"],
        ],
        "door-lock-hardware-repair-georgetown-tx" => [
            "slug" => "door-lock-hardware-repair-georgetown-tx",
            "short_title" => "Doors, locks & hardware",
            "title" => "Door, Lock & Hardware Repair in Georgetown, TX",
            "eyebrow" => "Doors that close, latch, slide, and lock properly",
            "meta_description" => "Storm door, sliding door, lock, smart lock, cabinet door, and hardware repairs for Sun City, Berry Creek, and Georgetown-area homes.",
            "intro" => "A door can feel like a small problem until it drags, will not latch, leaks air, or becomes difficult to lock. We look at alignment, hinges, strike position, rollers, weather exposure, and hardware before recommending a repair.",
            "summary" => "Services cover common residential door and hardware issues, including storm doors, sliding doors, smart locks, stops, blinds, and cabinet doors.",
            "icon" => "bi-door-open",
            "featured" => true,
            "tasks" => [
                "Storm door installation", "Sliding door repair", "Front door repair", "Door hardware replacement",
                "Door lock installation", "Smart lock installation", "Door blind installation", "Door stopper installation",
                "Cabinet door repair", "Garage door opener installation", "Garage remote troubleshooting",
            ],
            "details" => [
                ["name" => "Entry door adjustments", "description" => "Address sticking, rubbing, sagging, latching, strike, hinge, and weather-seal concerns."],
                ["name" => "Storm doors", "description" => "Install or adjust compatible storm doors, closers, handles, sweeps, and related hardware."],
                ["name" => "Sliding doors", "description" => "Troubleshoot accessible rollers, tracks, handles, locks, and alignment issues."],
                ["name" => "Locks and smart locks", "description" => "Replace compatible locksets and align the door so the hardware operates smoothly."],
                ["name" => "Cabinet doors", "description" => "Repair hinges, alignment, pulls, latches, and minor door damage."],
                ["name" => "Garage opener assistance", "description" => "Help with compatible opener installation or remote troubleshooting outside garage-door structural repair."],
            ],
            "good_fit" => ["A door that rubs or will not latch", "A planned lock or smart-lock replacement", "Loose, damaged, or misaligned residential hardware"],
            "caution" => null,
            "faqs" => [
                ["question" => "Can a sticking door usually be adjusted?", "answer" => "Often, but the cause may be hinges, frame movement, weather, swelling, hardware, or the slab itself. The repair depends on what is actually moving."],
                ["question" => "Do you replace entire garage doors?", "answer" => "No. Assistance is limited to compatible opener and remote tasks; garage door structural and spring work needs a specialist."],
            ],
            "service_types" => ["Door Hardware Repair", "Door Lock Installation", "Smart Lock Installation", "Sliding Door Repair"],
            "related" => ["lighting-security-smart-home-georgetown-tx", "cabinet-trim-carpentry-georgetown-tx", "home-inspection-repairs-georgetown-tx"],
        ],
        "cabinet-trim-carpentry-georgetown-tx" => [
            "slug" => "cabinet-trim-carpentry-georgetown-tx",
            "short_title" => "Cabinet, trim & small carpentry",
            "title" => "Cabinet, Trim & Small Carpentry Repair in Georgetown, TX",
            "eyebrow" => "Finish details that make a room feel cared for",
            "meta_description" => "Cabinet, baseboard, trim, shelf, closet, vanity, and small wood repairs for Sun City, Berry Creek, and Georgetown homes.",
            "intro" => "Loose trim, worn cabinet parts, damaged shelves, and small wood repairs can affect both appearance and daily use. We focus on well-fitted repairs and installations that stay within a manageable home-maintenance scope.",
            "summary" => "Carpentry services include trim, cabinets, shelves, closets, vanities, and small custom repairs—not full remodeling or large construction.",
            "icon" => "bi-hammer",
            "featured" => true,
            "tasks" => [
                "Baseboard installation", "Shoe molding installation", "Trim replacement", "Interior millwork repair",
                "Cabinet repair", "Bathroom cabinet repair", "Linen cabinet installation", "Vanity installation",
                "Cabinet door replacement", "Closet build-outs", "Shelf installation", "Shelf repair",
                "Fireplace trim updates outside gas, venting, and firebox systems", "Small custom wood repairs",
                "Countertop-related repairs", "Minor wood rot repair",
            ],
            "details" => [
                ["name" => "Cabinet repairs", "description" => "Repair alignment, hinges, doors, drawers, pulls, minor damage, and accessible cabinet components."],
                ["name" => "Trim and molding", "description" => "Replace or install baseboard, shoe molding, casing, and small areas of interior millwork."],
                ["name" => "Shelves and closets", "description" => "Install or repair practical shelving and modest closet components."],
                ["name" => "Vanities and linen cabinets", "description" => "Install compatible units when plumbing, wall, floor, and access conditions support the work."],
                ["name" => "Small wood repairs", "description" => "Address localized rot, splits, loose joints, and finish carpentry details."],
                ["name" => "Fireplace trim updates", "description" => "Complete limited trim changes that do not alter firebox, venting, gas, or structural systems."],
            ],
            "good_fit" => ["A cabinet door or drawer that no longer aligns", "A small run of damaged or missing trim", "Shelving or storage that needs secure, measured installation"],
            "caution" => "This service covers small carpentry repairs and installations. Full remodeling, structural changes, large built-ins, and gas or fireplace-system work are outside the marketed scope.",
            "faqs" => [
                ["question" => "Can you match existing trim?", "answer" => "Sometimes. A clear photo and sample help identify profile, dimensions, wood species, and finish. Exact matches depend on material availability and age."],
                ["question" => "Do you build full custom kitchens?", "answer" => "No. The focus is cabinet repair, hardware, shelves, trim, vanities, and other small carpentry tasks."],
            ],
            "service_types" => ["Cabinet Repair", "Trim Carpentry", "Shelf Installation", "Small Carpentry Repair"],
            "related" => ["door-lock-hardware-repair-georgetown-tx", "drywall-paint-touch-up-repair-georgetown-tx", "home-sale-punch-list-georgetown-tx"],
        ],
        "drywall-paint-touch-up-repair-georgetown-tx" => [
            "slug" => "drywall-paint-touch-up-repair-georgetown-tx",
            "short_title" => "Drywall, texture & touch-ups",
            "title" => "Drywall, Paint Touch-Up & Wall Repair in Georgetown, TX",
            "eyebrow" => "Small wall repairs, finished with restraint",
            "meta_description" => "Drywall patches, sheetrock repair, texture matching, water-damage wall repair, and repair-related paint touch-ups in Georgetown.",
            "intro" => "Wall damage is most noticeable when the patch shape, texture, sheen, or color catches the light. We plan the repair around the wall condition and keep paint work tied to the repaired area.",
            "summary" => "Services include small drywall and sheetrock repairs, texture work, wallpaper preparation, and paint touch-ups connected to the repair.",
            "icon" => "bi-bricks",
            "featured" => true,
            "tasks" => [
                "Drywall patching", "Drywall repair under windows", "Sheetrock repair", "Wall texture repair",
                "Paint touch-ups tied to repair work", "Water-damage wall repair after the moisture source is corrected",
                "Wallpaper repair or removal preparation",
            ],
            "details" => [
                ["name" => "Drywall patching", "description" => "Repair small holes, dents, cracks, access cuts, and localized damaged areas."],
                ["name" => "Texture repair", "description" => "Blend common wall textures as closely as practical within the repaired area."],
                ["name" => "Water-damage wall repair", "description" => "Repair affected wall material after the moisture source has been identified and corrected."],
                ["name" => "Paint touch-ups", "description" => "Prime and touch up the repair area using homeowner-provided or properly matched paint."],
                ["name" => "Wallpaper preparation", "description" => "Complete localized repair or removal preparation before a separate finish treatment."],
            ],
            "good_fit" => ["A doorknob hole or mounting damage", "A small stain or soft area after a leak was corrected", "Texture damage from a prior repair or removed fixture"],
            "caution" => "Full-room or whole-house painting is not offered. Active leaks, mold concerns, large moisture events, or structural movement should be evaluated before cosmetic repair.",
            "faqs" => [
                ["question" => "Will the repaired area be completely invisible?", "answer" => "Careful patching and texture work can blend well, but lighting, age, sheen, and paint fade may still make a localized repair visible."],
                ["question" => "Can you repair the wall before the leak is fixed?", "answer" => "The moisture source should be corrected and the area should be dry before closing and finishing the wall."],
            ],
            "service_types" => ["Drywall Repair", "Sheetrock Repair", "Paint Touch-Up Repair", "Wall Texture Repair"],
            "related" => ["cabinet-trim-carpentry-georgetown-tx", "home-inspection-repairs-georgetown-tx", "home-sale-punch-list-georgetown-tx"],
        ],
        "grab-bar-installation-sun-city-georgetown" => [
            "slug" => "grab-bar-installation-sun-city-georgetown",
            "short_title" => "Grab bars & home safety installs",
            "title" => "Grab Bar Installation in Sun City Georgetown, TX",
            "eyebrow" => "Secure placement for steadier everyday routines",
            "meta_description" => "Grab bars, shower bars, bathroom hardware, handholds, high-reach replacements, and accessibility punch lists in Sun City.",
            "intro" => "A grab bar is only useful when it is placed where the person naturally reaches and anchored to the right structure. We discuss the movement, location, wall construction, and bar style before drilling.",
            "summary" => "Safety-focused installations include shower and bathroom grab bars, hardware, high-reach replacements, and practical accessibility punch lists.",
            "icon" => "bi-universal-access",
            "featured" => true,
            "tasks" => [
                "Grab bar installation", "Shower grab-bar installation", "Bathroom safety hardware",
                "Towel bar installation", "Curtain rod installation", "Mirror hanging", "Blind installation",
                "Flag bracket installation", "TV mounting", "High-reach light and smoke detector replacement",
                "Home accessibility punch lists",
            ],
            "details" => [
                ["name" => "Shower grab bars", "description" => "Plan placement for entry, standing, turning, and shower-control use, then anchor appropriately."],
                ["name" => "Toilet-area supports", "description" => "Install compatible wall-mounted support where structure and clearances allow."],
                ["name" => "Bathroom hardware", "description" => "Install towel bars, mirrors, and related accessories with secure mounting."],
                ["name" => "High-reach replacements", "description" => "Replace accessible lights and smoke detectors without asking homeowners to climb."],
                ["name" => "Accessibility punch lists", "description" => "Review a homeowner-prepared list of small changes that may improve everyday use."],
            ],
            "good_fit" => ["A shower or tub entry that needs a reliable handhold", "A planned post-surgery or aging-in-place update", "A home safety list from the homeowner, family, or care professional"],
            "caution" => "Grab bars are not a substitute for professional accessibility guidance or a qualified assessment. Placement and anchoring depend on the user, wall construction, clearances, and product instructions.",
            "faqs" => [
                ["question" => "Where should a shower grab bar go?", "answer" => "Placement should match how the user enters, stands, turns, and reaches for controls. Wall structure and the product's mounting requirements also determine what is possible."],
                ["question" => "Can a towel bar be used as a grab bar?", "answer" => "No. Towel bars are not designed or anchored for body-weight support. Use a product intended and installed as a grab bar."],
            ],
            "service_types" => ["Grab Bar Installation", "Bathroom Safety Hardware", "Home Accessibility Punch List"],
            "related" => ["handyman-services-sun-city-georgetown", "home-inspection-repairs-georgetown-tx"],
        ],
        "exterior-home-maintenance-georgetown-tx" => [
            "slug" => "exterior-home-maintenance-georgetown-tx",
            "short_title" => "Minor exterior maintenance",
            "title" => "Minor Exterior Home Maintenance in Georgetown, TX",
            "eyebrow" => "Focused repairs that help keep weather outside",
            "meta_description" => "Gutter, downspout, fascia, minor siding, caulking, mailbox, animal-entry, house-washing, and dryer-vent assistance for Georgetown-area homes.",
            "intro" => "Small exterior defects can direct water where it does not belong or let pests and weather reach vulnerable materials. We focus on visible, accessible maintenance items—not roofing or large exterior construction.",
            "summary" => "Exterior services include localized gutter, downspout, fascia, siding, sealant, mailbox, animal-entry, washing, and vent-related assistance.",
            "icon" => "bi-house-check",
            "featured" => false,
            "tasks" => [
                "Gutter repair", "Downspout repair", "Fascia repair", "Minor siding repair", "Exterior rot repair",
                "Mailbox repair", "Bird entry prevention", "Squirrel damage repair", "Exterior caulking and sealing",
                "House washing", "Dryer vent assistance",
            ],
            "details" => [
                ["name" => "Gutters and downspouts", "description" => "Repair accessible loose sections, joints, outlets, extensions, and drainage-direction issues."],
                ["name" => "Fascia and minor siding", "description" => "Address localized damage or rot where the work remains small and accessible."],
                ["name" => "Exterior sealing", "description" => "Renew failed caulking at selected joints and penetrations after reviewing the likely moisture path."],
                ["name" => "Mailbox repairs", "description" => "Repair or replace compatible mailbox hardware and small support components."],
                ["name" => "Bird and squirrel entry prevention", "description" => "Close small accessible entry points after confirming the area is clear and the repair is appropriate."],
                ["name" => "House washing and dryer vent assistance", "description" => "Help with limited exterior cleaning and accessible vent maintenance within the approved scope."],
            ],
            "good_fit" => ["A loose downspout or isolated gutter leak", "A small caulk or trim failure", "A minor exterior punch-list item below the roofline"],
            "caution" => "Exterior-visible work may require HOA or permit review. Confirm HOA, permit, utility, and manufacturer requirements. Roofing, full siding replacement, deck work, and large exterior construction are not offered.",
            "faqs" => [
                ["question" => "Do you repair roofs?", "answer" => "No. Roofing and roof repair are outside the marketed scope. Minor accessible fascia, gutter, downspout, siding, and sealant work may be appropriate."],
                ["question" => "Can you seal an animal entry immediately?", "answer" => "The area should first be checked to avoid trapping wildlife. The opening, access, material, and animal activity determine the right next step."],
            ],
            "service_types" => ["Gutter Repair", "Downspout Repair", "Minor Exterior Repair", "Exterior Caulking"],
            "related" => ["handyman-services-sun-city-georgetown", "home-inspection-repairs-georgetown-tx"],
        ],
        "home-inspection-repairs-georgetown-tx" => [
            "slug" => "home-inspection-repairs-georgetown-tx",
            "short_title" => "Home inspection repairs",
            "title" => "Home Inspection Repairs in Georgetown, TX",
            "eyebrow" => "Turn the report into a workable repair plan",
            "meta_description" => "Home inspection repair lists for Sun City, Berry Creek, and Georgetown homes, with clear work plans and licensed help when required.",
            "intro" => "Inspection reports can make a collection of small items feel like one large project. We help sort repair notes into practical handyman tasks, licensed-trade items, specialist work, and questions for the inspector or seller.",
            "summary" => "The result is a clearer scope for common fixture, hardware, trim, wall, safety, and maintenance repairs—without pretending every report note has the same priority.",
            "icon" => "bi-clipboard-check",
            "featured" => true,
            "tasks" => [
                "Inspection report review and repair-list organization", "Approved handyman inspection repairs",
                "Licensed plumbing and electrical item routing", "Specialist-scope separation", "Completion-note organization",
            ],
            "details" => [
                ["name" => "Report review", "description" => "Organize the relevant pages, photos, and repair notes into a clear working list."],
                ["name" => "Handyman repairs", "description" => "Complete approved door, hardware, fixture, trim, wall, safety, and maintenance items."],
                ["name" => "Licensed-trade routing", "description" => "Identify electrical or plumbing items that need an appropriately licensed professional."],
                ["name" => "Specialist boundaries", "description" => "Separate roofing, HVAC, structural, pest, or other out-of-scope work from the handyman list."],
                ["name" => "Completion notes", "description" => "Keep the work list organized so the homeowner can track what was addressed."],
            ],
            "good_fit" => ["A buyer's inspection with several small repair notes", "A seller preparing agreed-upon repairs", "A homeowner using an inspection as a maintenance roadmap"],
            "caution" => "Sun City Home Repair does not reinterpret or certify an inspection. Repairs are scoped from the visible condition and may require specialist or licensed-trade review.",
            "faqs" => [
                ["question" => "Can you complete every item on an inspection report?", "answer" => "Not necessarily. Roofing, HVAC, structural, gas, large construction, and other specialist items are outside the marketed scope. The report can be divided into the right categories."],
                ["question" => "What should I send with my request?", "answer" => "Send the relevant report pages, clear photos, the property ZIP code, timing needs, and any repair agreement that limits the scope."],
            ],
            "service_types" => ["Home Inspection Repairs", "Punch-List Repairs", "Home Maintenance"],
            "related" => ["handyman-services-sun-city-georgetown", "home-sale-punch-list-georgetown-tx", "drywall-paint-touch-up-repair-georgetown-tx"],
        ],
        "home-sale-punch-list-georgetown-tx" => [
            "slug" => "home-sale-punch-list-georgetown-tx",
            "short_title" => "Home sale punch lists",
            "title" => "Home Sale Punch-List Repairs in Georgetown, TX",
            "eyebrow" => "Tidy up the details before listing or closing",
            "meta_description" => "Home sale punch-list repairs, fixture updates, hardware, trim, drywall, and maintenance help in Sun City and Georgetown.",
            "intro" => "Before photos, showings, or closing, small defects become easier to notice. A focused punch list helps homeowners prioritize function, presentation, and agreed repairs without drifting into a full remodel.",
            "summary" => "We handle approved small repairs and installations, coordinate licensed-trade items when required, and keep the list centered on practical next steps.",
            "icon" => "bi-list-check",
            "featured" => false,
            "tasks" => [
                "Pre-listing repair lists", "Door and hardware repairs", "Localized wall and trim repairs",
                "Compatible fixture updates", "Agreed closing repair lists", "Move-out punch-list repairs",
            ],
            "details" => [
                ["name" => "Pre-listing walk-through lists", "description" => "Work from the homeowner's priorities to organize visible and functional repair items."],
                ["name" => "Door and hardware details", "description" => "Address sticking doors, loose handles, missing stops, locks, and cabinet hardware."],
                ["name" => "Wall and trim repairs", "description" => "Complete localized drywall, texture, touch-up, baseboard, and trim work."],
                ["name" => "Fixture updates", "description" => "Replace compatible lights, fans, faucets, detectors, and other fixtures within the approved scope."],
                ["name" => "Closing repair lists", "description" => "Address agreed items with clear boundaries and route specialist work appropriately."],
            ],
            "good_fit" => ["A short list before listing photos", "Buyer-requested repairs within an agreed scope", "Small move-out repairs after furniture and wall hangings are removed"],
            "caution" => "No repair can guarantee a sale, appraisal result, inspection outcome, or closing date. Large remodeling and specialist work remain outside the marketed scope.",
            "faqs" => [
                ["question" => "How early should I start a pre-sale punch list?", "answer" => "Start early enough to review parts, materials, licensed-trade needs, and any follow-up before photography, listing, or closing deadlines."],
                ["question" => "Can you help decide what matters most?", "answer" => "We can help organize function, visible condition, and scope, but pricing, disclosure, and negotiation decisions should stay with the homeowner and their real-estate professionals."],
            ],
            "service_types" => ["Home Sale Punch List Repairs", "Make-Ready Home Repairs", "Handyman Services"],
            "related" => ["home-inspection-repairs-georgetown-tx", "handyman-services-sun-city-georgetown", "cabinet-trim-carpentry-georgetown-tx"],
        ],
    ],
];
